@WarmachineAPI_HostAddress = http://localhost:5069

GET {{WarmachineAPI_HostAddress}}/api/factions
Accept: application/json

###

POST {{WarmachineAPI_HostAddress}}/api/factions
Content-Type: application/json

{
  "name": "Cygnar",
  "description": "A steam-powered industrial nation."
}

###
